set_slots:
  fields:
    config_entry:
      required: true
      selector:
        config_entry:
          integration: nordpool_scheduler
    slots:
      required: true
      example: '[{"start": "2025-10-08T22:00:00+00:00", "state": "on"}]'
      selector:
        object:

clear_schedule:
  fields:
    config_entry:
      required: true
      selector:
        config_entry:
          integration: nordpool_scheduler
